import { gameInfo } from "./gameInfo.interface";

  export const normalGameInfo: gameInfo = {
    name: 'normal',
    borderSize: 10,
    menuSize: 90,
    ysize: 500,
    xsize: 800,
    gamey: 110,
    gamex: 10,
    ballx: 100,
    bally: 100,
    barDist: 20,
    oneBary: 10,
    twoBary: 10,
    barSpeed: 2,
    ballDirx: -1,
    ballDiry: -0.4,
    ballSpeed: 4.0,
    gamexsize: 780,
    gameysize: 380,
    barLarge: 10,
    oneScore: 0,
    twoScore: 0,
    ballDeb: 10,
    ballSize: 10,
    barSize: 100,
    numberSize: 10,
    oneBarColor: '#ffffff',
    twoBarColor: '#ffffff',
    ballColor: '#ffffff',
    backgroundColor: '#000000',
    borderColor: '#ffffff',
    oneScoreColor: '#ffffff',
    twoScoreColor: '#ffffff',
    menuColor: '#000000',
    numberSideDist: 10,
    numberTopDist: 10,
    upBallSize: false,
    downBallSize: false,
    id: 10,
    compteur: 3,
  };
