import { gameInfo } from "./gameInfo.interface";

  export const normalGameInfo: gameInfo = {
    name: 'normal',
    borderSize: 10,
    menuSize: 90,
    ysize: 500,
    xsize: 800,
    gamey: 110,
    gamex: 10,
    ballx: 100,
    bally: 100,
    barDist: 20,
    oneBary: 10,
    twoBary: 10,
    barSpeed: 2,
    ballDirx: -1,
    ballDiry: -0.4,
    ballSpeed: 4.0,
    gamexsize: 780,
    gameysize: 380,
    barLarge: 10,
    oneScore: 0,
    twoScore: 0,
    ballDeb: 150,
    ballSize: 10,
    barSize: 100,
    itemx: 40,
    itemy: 40,
    itemSize: 0,
    numberSize: 10,
    oneBarColor: 'white',
    twoBarColor: 'white',
    ballColor: 'white',
    backgroundColor: 'black',
    borderColor: 'white',
    oneScoreColor: 'white',
    twoScoreColor: 'white',
    menuColor: 'black',
    numberSideDist: 10,
    numberTopDist: 10,
  };
