export enum UserEventType {
  NOEVENT = 'NOEVENT',
  FRIENDREQUESTRECEIVED = 'FRIENDREQUESTRECEIVED',
  FRIENDSHIPREMOVED = 'FRIENDSHIPREMOVED',
  FRIENDREQUESTREVOKED = 'FRIENDREQUESTREVOKED',
  FRIENDREQUESTACCEPTED = 'FRIENDREQUESTACCEPTED',
  USERBLOCKED = 'USERBLOCKED',
  USERUNBLOCKED = 'USERUNBLOCKED',
  ADDEDTOCHAN = 'ADDEDTOCHAN',
  KICKFROMCHAN = 'KICKFROMCHAN',
  BANFROMCHAN = 'BANFROMCHAN',
  MUTEINCHAN = 'MUTEINCHAN',
  CHANDELETION = 'CHANDELETION',
  DEPARTUREFROMCHAN = 'DEPARTUREFROMCHAN',
}

export type UserEvent = {
  type: UserEventType;
  initiatorId: number;
  recipientId: number;
};
