export enum UserEventType {
  NOEVENT = 'NOEVENT',
  FRIENDREQUESTRECEIVED = 'FRIENDREQUESTRECEIVED',
  FRIENDSHIPREMOVED = 'FRIENDSHIPREMOVED',
  FRIENDREQUESTREVOKED = 'FRIENDREQUESTREVOKED',
  FRIENDREQUESTACCEPTED = 'FRIENDREQUESTACCEPTED',
  USERBLOCKED = 'USERBLOCKED',
  USERUNBLOCKED = 'USERUNBLOCKED',
  ADDEDTOCHAN = 'ADDEDTOCHAN',
  DEPARTUREFROMCHAN = 'DEPARTUREFROMCHAN',
  KICKFROMCHAN = 'KICKFROMCHAN',
  BANFROMCHAN = 'BANFROMCHAN',
  UNBANFROMCHAN = 'UNBANFROMCHAN',
  MUTEINCHAN = 'MUTEINCHAN',
  UNMUTEINCHAN = 'UNMUTEINCHAN',
  CHANDELETION = 'CHANDELETION',
  USERDELETED = 'USERDELETED',
  OWNERMADE = 'OWNERMADE',
  ADMINMADE = 'ADMINMADE',
  DEMOTEADMIN = 'DEMOTEADMIN',
}

export type UserEvent = {
  type: UserEventType;
  userId: number;
  channelId: number;
  recipientIds: number[];
};
